global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['app:5000']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']
